= DotShip!

It's a simple but effective dotfile manager. This project is my first time trying zig.
So don't judge ЁЯШЛ.

== Files
* files-DB
    It uses TOML as a place to track list of files to keep track of.
* lockfile
    JSON file that keeps the time and hash of the files.
* files/
    folder containing the files. They are named (there path but . instead of /)

=== Cli Refrences

* [ ] `sync` тоз
    It parses the lockfile, then parses the DB. and produces a list of task (dots to be updated). Then executes them.
* [x] `init` тоз
    On a new Installation creates the directory and initilizes files.
* [x] `help` тоз
    Usage info!
* [ ] `Add/Remove` тоз
    Provides an Interface to edit DB. If so wishes.
* [ ] `Push/Git` тоз
    Git pushes changes to the repo. Automatically toggled with sync.
* [ ] `gen-systemd` тоз
    Generates a systemd timer. So the script syncs weeakly withouth user input.

=== History

11-jul-24-06-20-00:: Improved Dev-Ex. And started using idomatic zig. Getting better. First time I feel like. I'm getting hang of the language.
10-jul-24-08-57-00:: Fresh take. Started by visualizing the flow. And then implementing it.
                        Didn't have to fight the stdlib this time around. Through errors are still pretty mid.
16-jun-24-03-28-00:: Got frustated with using `zig` standard library. It's not mature enough.
17-jun-24-01-30-38:: Finished the init function. Documentation on standard library is still lacking.
                    Although, right now struggled with errors. Probably cause this is my first strict type language.
18-jun-24-10-15-15:: Started work on add. Just finnished refactoring to add usage info()!
